### ISSUE TITLE
mp3 files?

### ISSUE THREAD

**Issue by FatPanther** [binaryage/drydrop#13]
Hi, my site has a couple of mp3 files - github serves them up fine from their raw URL, but in drydrop/GAE I get this error:

404 - Unable to process the page
The request to API call datastore_v3.Put() was too large

Thanks

**Comment by darwin** [comment]
ah, drydrop is not suitable for hosting large files. datastore cache has its limits. you should probably use CDN to host big files and images

**Comment by FatPanther** [comment]
Figured that might be the case - thanks
