### ISSUE TITLE
Rake Not Working On Windows?

### ISSUE THREAD

**Issue by micahthomas** [binaryage/drydrop#14]
I did:
rake upload project=projectname
and I get error saying "uninitialized constant Object::PLATFORM"

<pre>C:\Users\Micah\Downloads\drydrop>rake upload project=thomasmicahtk
(in C:/Users/Micah/Downloads/drydrop)
rake aborted!
uninitialized constant Object::PLATFORM
C:/Users/Micah/Downloads/drydrop/rakefile:15:in `<top (required)>'
(See full trace by running task with --trace)</pre>

**Comment by darwin** [comment]
I think I saw something like this on OSX when running rake under ruby 1.9

originally the script was written for ruby 1.8

**Comment by micahthomas** [comment]
oh, thanks for the reply
