### ISSUE TITLE
Cannot `rake upload project=xxxxx`

### ISSUE THREAD

**Issue by ghost** [binaryage/drydrop#17]
Whenever I try to "rake upload project=xxxx", I get the following error:
`(in /Users/natan/Development/xxxxxx)
rake aborted!
uninitialized constant Object::PLATFORM
/Users/natan/Development/xxxxxx/rakefile:15:in`<top (required)>'
(See full trace by running task with --trace)`

And when I try "rake --trace upload project=xxxxxx", I get this:
`rake aborted!
uninitialized constant Object::PLATFORM
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2503:in`const_missing'
/Users/natan/Development/treepunch3r/rakefile:15:in `<top (required)>'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2383:in`load'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2383:in `raw_load_rakefile'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2017:in`block in load_rakefile'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2016:in`load_rakefile'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2000:in `block in run'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/rake-0.8.7/bin/rake:31:in`<top (required)>'
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19:in`<main>'`

Ruby version: ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.6.0]
Rake version: rake, version 0.8.7
I'm running OS X Snow Leopard.
Ruby is located in /usr/bin/ruby.

Thanks in advance!

**Comment by darwin** [comment]
Yes, the rakefile was written for ruby 1.8.x

Let me try to fix it now.

**Comment by ghost** [comment]
OK, thanks!
