### ISSUE TITLE
Rake ruby needed?

### ISSUE THREAD

**Issue by Yuripetusko** [binaryage/drydrop#19]
Hi, it doesn't anywhere specified that I need ruby to run rake command. 

I get error for this command: rake upload project=yuripetusko
(in /Users/petusko/Sites/Google App/website/drydrop)
rake aborted!
You must "sudo gem install rb-appscript"

OR

uklon-06299:yuripetusko petuskoj$ rake upload project=yuripetusko
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/rake-0.8.3/lib/rake.rb:2343:in `raw_load_rakefile'

So I wen and just copied all files to google app engine folder and used GUI to deploy it. but then I dont see anything on my appengine appspot website. Can you confirm that I need to have ruby and to run that rake command?

**Comment by darwin** [comment]
I don't remember the details but it should work if you copy it as plain folder.

You may look into rakefile what it does. It just zips modules and
patches few strings.

On Mon, Jun 13, 2011 at 12:00 PM, Yuripetusko
reply@reply.github.com
wrote:

**Comment by Yuripetusko** [comment]
Ok, got it working. Had to buy and install Xcode from appstore as it has gcc which I required to install rubyzip etc. now working good
